### ISSUE TITLE
mouse middle click

### ISSUE THREAD

**Issue by Crazy-Hopper** [davidedmundson/xembed-sni-proxy#14]
Hi, could you please take a look at whether it is possible to proxy the mouse middle clicks to SNIs?

**Comment by davidedmundson** [comment]
ooh, I can.

SNI's emit "SecondaryActivate" 
should be simple enough.

Want to try and make a patch? Just copy and paste Activate in sniproxy, then make it send mouse button 2.

**Comment by Crazy-Hopper** [comment]
Huh! You did it already, just with button 1 instead of button 2 :-)

**Comment by davidedmundson** [comment]
oh, thanks.

Pushed
