### ISSUE TITLE
Lacking documentation on how to setup

### ISSUE THREAD

**Issue by DominicWatson** [davidedmundson/xembed-sni-proxy#17]
Please provide build instructions and how you expect this to be used in any working system. I'm stuck atm getting `cmake` to run without errors (dependencies) and I only figured I needed to run that from reading another open issue (#5).

A couple of lines in the README should do it :)

_Update_
FYI. I managed to resolve dependencies and get `cmake`, `make` and `make install` to run in my Kubuntu system.

I personally needed to install Ubuntu packages:

```
cmake
extra-cmake-modules
make
libxcb-*
libkf5windowsystem-dev
libqt5x11extras5-dev
qtdeclarative5-dev
qtdeclarative5-dev-tools
libqt5declarative5
qtquick1-5-dev
qtscript5-dev
libqt5svg5-dev
qttools5-dev-tools
qttools5-dev
libqt5opengl5-dev
qtquick1-qml-plugins
```

(Some of these may not have been necessary).

**Comment by davidedmundson** [comment]
I intend to merge into plasma-workspace for Plasma 5.5, which has it's own setup readme.

Not really worth it for 1.5 months, sorry.

**Comment by DominicWatson** [comment]
A couple of lines in a README will take minutes and save people like me much more time than that. I'd urge you to reconsider.

**Comment by tehnick** [comment]
@davidedmundson
I suppose you have created this git repo for testing purposes, so it is quite strange that you pushing away people from testing of the program. 1.5 month is a quite long period of time and many bugs could be found during it.

**Comment by tehnick** [comment]
@DominicWatson 
Why you have not added a list of build dependencies?

**Comment by tehnick** [comment]
When I have been preparing packages for Debian and Ubuntu, I have checked build dependencies of the program by reading CMakeLists.txt and by testing build in a clean environment (using cowbuilder). If anyone will have to do the same job in other distros, it is just wasting of their time...

**Comment by tehnick** [comment]
BTW my list list of build dependencies is currently looks like this:
http://anonscm.debian.org/cgit/pkg-kde/kde-extras/xembed-sni-proxy.git/tree/debian/control#n6

**Comment by tehnick** [comment]
@DominicWatson
BTW there is a PPA with xembed-sni-proxy for usual Ubuntu users (who cannot build program themself):
https://launchpad.net/~tehnick/+archive/ubuntu/xembed-sni-proxy

**Comment by davidedmundson** [comment]
RE: your control file.
GNOME Shell doesn't support SNIs.

**Comment by tehnick** [comment]
@davidedmundson
Do you mean that AppIndicator extension is not installed by default?

**Comment by davidedmundson** [comment]
I knew their shell didn't, we've had some "discussions" with their maintainers.  Didn't think to look at extensions. That's cool.

**Comment by DominicWatson** [comment]
Nice one. @tehnick I didn't include dependencies list because I'm a complete n00b at building things with `cmake` / `make` so wasn't sure of the best way to document this (presuming different distros will have different packages to fulfil these dependencies). Thanks for the heads up re the PPA.
