### ISSUE TITLE
Chromium and Hangouts

### ISSUE THREAD

**Issue by tgurr** [davidedmundson/xembed-sni-proxy#2]
I've uninstalled libappindicator and related stuff and installed xembed-sni-proxy (git master), this is how Chromium and the Hangouts plugin show up after logging in to a Plasma session:
![chromium_and_hangouts](https://cloud.githubusercontent.com/assets/414984/10200521/4ff4bb32-67a7-11e5-9e14-15e52c01e819.jpg)
Left and right clicking the icons doesn't work.

After killing and restarting chromium multiple times it can end up like this:
![chromium_and_hangouts2](https://cloud.githubusercontent.com/assets/414984/10200548/6ceb785c-67a7-11e5-9f8d-5f8cb9dcf170.jpg)
And left clicking the Hangouts icon opens up the gui window, but right clicking any of Chromium or Hangouts still doesn't do anything.

**Comment by davidedmundson** [comment]
Thanks

> I've uninstalled libappindicator and related stuff

To make sure we're clear; you don't want to be doing that for daily usage. libappindicator directly is obviously the much much better approach.

But I want to fix this as the cause is probably going to affect some other apps that don't have that option.

I've got chromium, how do I make it show those 2 systrays?

**Comment by tgurr** [comment]
> you don't want to be doing that for daily usage

I guess you meant not yet for daily usage? Or is the xembed-sni-proxy never meant to be a replacement? I just did it to test and to create a package for our distribution. I also didn't test what happens when both are installed (perhaps the icons show up twice then?).

> I've got chromium, how do I make it show those 2 systrays?

It comes up when you install the Hangouts Chrome/Chromium plugin:
https://chrome.google.com/webstore/detail/hangouts/nckgahadagoaajjgafhacjanaoiihapd
Maybe you also need to install the google-talkplugin/hangouts (system/browser plugin) for it to work: https://www.google.com/tools/dlpage/hangoutplugin
Many distributions have packages for it, mostly under the old name google-talkplugin.

**Comment by davidedmundson** [comment]
Thanks. That's what I needed.

As for the comment. Its not a replacement but a fallback if appindicator can't be used.

Things shouldn't show up twice, ... But client code can do all manner of unpredictable things.

**Comment by tgurr** [comment]
Short update, with the latest changes the icons began to show up, they look a bit tattered
![hangout3](https://cloud.githubusercontent.com/assets/414984/10246042/f1d31b26-690d-11e5-9a1e-fda13a72eabe.jpg)
and not as beautiful as with libappindicator and the background sometimes switches to black:
![hangout4](https://cloud.githubusercontent.com/assets/414984/10246045/f6b614a4-690d-11e5-85f7-159c2864a339.jpg)
but they're displayed now. The left and right clicking however still doesn't work.

**Comment by tgurr** [comment]
With the latest changes everything seems to work fine so far, the background doesn't turn to black anymore, they're scaled properly and left and right clicking them (Chromium/Hangouts) works. The only thing left is that the icons look a bit tattered, but that's not what my issue was about and it doesn't affect functionality.
