### ISSUE TITLE
Dropbox peculiarity

### ISSUE THREAD

**Issue by Crazy-Hopper** [davidedmundson/xembed-sni-proxy#25]
Hi, throughout all the possible xembed clients I tested, only the Dropbox icon gets garbled background copied from where the embedded window got mapped. All other windows don't exhibit such behaviour. Any idea why Dropbox would be in any way different?

**Comment by vanoudt** [comment]
Well, the first thing to do is to bug them to use a version of Qt that supports SNI (they say that they don't)... Not that that helps fix their weird xembed. Got the same symptoms here... see #6

**Comment by Crazy-Hopper** [comment]
> apt-cache show dropbox | grep Dep
> Depends: procps, python-gtk2 (>= 2.12), python (>= 2.5), libatk1.0-0 (>= 1.20.0), libc6 (>= 2.4), libcairo2 (>= 1.6.0), libglib2.0-0 (>= 2.16.0), libgtk2.0-0 (>= 2.12.0), libpango1.0-0 (>= 1.20.1), lsb-release

I see no Qt here at all.

On the other hand, the whole purpose of this project is to make apps that aren't ready for SNI not to be lost.

**Comment by Crazy-Hopper** [comment]
Closing this as duplicate of #6.

**Comment by tehnick** [comment]
> Any idea why Dropbox would be in any way different?

Personally I do not use Dropbox. But I have read that current versions of Dropbox use Qt5 < 5.4.2 and in this version of Qt5 systray icons were not fixed yet.

**Comment by tehnick** [comment]
> I see no Qt here at all.

This is because unlike Skype and some other proprietary software Dropbox do not use system libraries but uses libraries shipped in the package. Try something like `dpkg -L dropbox` if you use Debian-based system to see the list of files.

**Comment by tehnick** [comment]
> On the other hand, the whole purpose of this project is to make apps that aren't ready for SNI not to be lost.

Indeed. Just wait until Dropbox developers will update their packages. Systray-related bugs are well known to them.
