### ISSUE TITLE
kde plasma 5.12

### ISSUE THREAD

**Issue by elgui02** [davidedmundson/xembed-sni-proxy#5]
I have a 5.12 plasma version, i doesn't found compile instructions , on the source i execute:
1. cmake . 
2. make
3. make install 

Do you have a instructions install?

**Comment by FadeMind** [comment]
What Linux Distro You have?

**Comment by ghost** [comment]
Same Problem here. I'm running Debian Testing.

**Comment by paulolieuthier** [comment]
Are you guys running it? AFAIK running `xembedsniproxy` will start the daemon and new xembed icons will appear in the status notifier.

**Comment by elgui02** [comment]
When i run xembedsniproxy and works but without icon 
![image](https://cloud.githubusercontent.com/assets/355838/10373925/9324ed44-6dad-11e5-9a87-23b5dffc6968.png)

**Comment by tehnick** [comment]
This bug report might be closed now.
